-- Q1. What are the top 5 most profitable routes?

SELECT origin, destination, SUM(ticket_price) AS total_revenue
FROM Bookings B
JOIN Flights F ON B.flight_id = F.flight_id
GROUP BY origin, destination
ORDER BY total_revenue DESC
LIMIT 5;

-- Q2. who are the top 5 customers by total spending

SELECT C.name, SUM(B.ticket_price) AS total_spent
FROM Bookings B
JOIN Customers C ON B.customer_id = C.customer_id
GROUP BY C.name
ORDER BY total_spent DESC
LIMIT 5;


-- Q3. Which flights had the highest load factors (seat utilization)?

SELECT F.flight_id, F.origin, F.destination,
       COUNT(B.booking_id)*1.0 / F.total_seats AS load_factor
FROM Flights F
LEFT JOIN Bookings B ON F.flight_id = B.flight_id
GROUP BY F.flight_id, F.origin, F.destination, F.total_seats
ORDER BY load_factor DESC
LIMIT 5;


-- Q4. How much revenue is generated by each loyalty tier?

SELECT C.loyalty_status, SUM(B.ticket_price) AS revenue
FROM Bookings B
JOIN Customers C ON B.customer_id = C.customer_id
GROUP BY C.loyalty_status
ORDER BY revenue DESC;


-- Q5. Which payment methods are most popular (completed only)?

SELECT method, COUNT(*) AS usage_count
FROM Payments
WHERE status = 'Completed'
GROUP BY method
ORDER BY usage_count DESC;
